# Generated by Django 5.2.1 on 2026-06-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('sms_status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
