# Generated by Django 5.2.1 on 2026-06-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_weight', models.FloatField()),
                ('date_of_birth', models.DateField()),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
